spring:
  application:
    name: CAMUNDA
  datasource:
    url: jdbc:oracle:thin:@10.2.72.201:1521:OCEAN
    username: CAMUNDA
    password: CAMUNDA
    driver-class-name: oracle.jdbc.driver.OracleDriver



